version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
    - checkout

    - run:
      name: Prepare .config files
      command: echo "repo_token:\ $COVERALLS_REPO_TOKEN" > ./.coveralls.yml

    - run: 
      name: install bundle
      command: bundle install

    - run:
      name: Install CocoaPods
      command: pod install

    - run:
      name: Run tests
      command: fastlane scan
      environment:
        SCAN_DEVICE: iPhone 6
        SCAN_SCHEME: demoProjectObjectiveC

    - run: 
      name: Waitting Coverage generated
      command: sleep 5

    - run:
      name: Test Coverage
      command: bundle exec slather