# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout

      - run:
          name: Prepare .config files
          command: echo "repo_token:$COVERALLS_REPO_TOKEN" > ./.coveralls.yml

      - run: 
          name: install bundle
          command: bundle install

      - run:
          name: Install CocoaPods
          command: pod install

      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: demoProjectObjectiveC
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
           
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

      - run: 
          name: Waitting Coverage generated
          command: sleep 5

      - run:
          name: Test Coverage
          command: bundle exec slather