# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout

      - run:
          name: Prepare .config files
          command:
            echo "repo_token:$REPO_TOKEN" > ./.coveralls.yml

      - run: 
          name: install bundle
          command: bundle install

      - run:
          name: Install CocoaPods
          command: pod install

      - run:
          name: Test Coverage
          command: bundle exec fastlane ios unit_test
