# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    run_tests(workspace: "demoProjectObjectiveC.xcworkspace",
                devices: "iPhone 6",
                scheme: "demoProjectObjectiveCTests")
  end
  desc "Description of what the lane does"
  lane :coverage do
    lcov(project_name: "demoProjectObjectiveC.xcworkspace",
          scheme: "demoProjectObjectiveCTests")
  end
  lane :cover do
    scan(code_coverage: true,
          device: "iPhone 6")
  end
end
